### ISSUE TITLE
Outdated Template.  

### ISSUE THREAD

**Issue by louiss0** [Ahryman40k/nx-vitepress#1]
| name                    | version  |
| ----------------------- | -------- |
| vitepress               | alpha-76 |
| Ahryman40k/nx-vitepress | 15.1.1   | 

The template file is outdated it the API for creating a `vitepress` page is different and it will no longer be too convenient for me to use this template. Please change the template so that it will be convenient for people to use.  

**The index.template.md file in this repo**
```yaml
home: true
heroImage: /logo.png
heroAlt: Logo image
heroText: Vitepress
tagline: Nx powered project
actionText: Get Started
actionLink: /guide/
features:
  - title: Theming 
    details: Dark and light mode are already activated.
  - title: Navigation
    details: Enjoy having a ready-to-use navigation bar.
  - title: Sidebar 
    details: Custom sidebar defined for _/guide_ route.

```

**The new API**

```yaml

home: true
 image: 
  src: /logo.png
  alt: Logo image
 text: Vitepress
 tagline: Nx powered project

features:
  - title: Theming 
    details: Dark and light mode are already activated.

  - title: Navigation
    details: Enjoy having a ready-to-use navigation bar.

  - title: Sidebar 
    details: Custom sidebar defined for _/guide_ route.

```

**These two are also outdated according to the docs.** 

```yaml
actionText: Get Started
actionLink: /guide/
```

Link to the docs for the home section [here](https://vitepress.dev/reference/default-theme-home-page)
